version: '3.8'
services:
  client:
    container_name: meli-frontend
    restart: always
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - ${PORT}:${PORT}

volumes:
  data: {}
